### PR TITLE
Map bits/chrono.h to chrono

### PR DESCRIPTION
**Pull request by correaa**
As discussed in https://github.com/include-what-you-use/include-what-you-use/issues/1552

Not sure if `@` is needed

### CODE REVIEW

**Comment by kimgr** [comment]
@correaa Thanks! `@` is not necessary; it's a marker to say that the mapping contains a regex pattern rather than an exact match.

**Comment by kimgr** [comment]
This looks good to me (I would prefer it in a single commit, but I can squash it on merge). I'll just postpone merging until we've managed to fix the build error on master, so we can see that it runs clean.

**Comment by kimgr** [comment]
@correaa Master is back to green; could I ask you to rebase and repush to run the build steps with this patch? Thanks.

**Comment by correaa** [comment]
I didn't know how to rebase from the Github GUI, so accidentally opened a different PR #1560

**Pull request closed without merging**
