### PR TITLE
Fix warnings related to clang-12

### PR DESCRIPTION
**Pull request by storoj**

### CODE REVIEW

**Comment by kimgr** [comment]
> Fix "loop variable ... binds to a temporary constructed" (-Wrange-loop-construct)

Commit subject too long. I usually try to avoid mentioning tools and warnings in the commit subject and focus on what was corrected. I suggest something like:

> Fix reference-to-temporary in header-search
>
> The map range iterator returns a 'const pair<const string, ...>&', not the
> expected 'const pair<string, ...>&', and the compiler helpfully converts
> to a temporary. Make the types match.
>
> Found by Clang's -Wrange-loop-construct 

But I agree that your original `auto` solution is probably nicer. Something like:
```
for (const auto& entry : ...)
```

would be less susceptible to bugs without losing readability, so if you want to go back to that (and adjust the commit message) that would probably be even better.

**Comment by kimgr** [comment]
Oh, and for the new enumerators, could you mention in the commit message the Clang commit sha that introduced them, rather than clang major version? Thanks.

**Comment by storoj** [comment]
Thanks @kimgr 

I addressed your comments:
* switched back to `const auto&`;
* updated the commit message for `-Wrange-loop-construct` fix;
* mentioned `sha`s from llvm-project that introduced enumeration values that were unhandled;

**Comment by kimgr** [comment]
Nice, :+1:

**Pull request merged**
