### PR TITLE
Convert CreateCompilerInstance function to IwyuDriver class

### PR DESCRIPTION
**Pull request by trixirt**
Show use of compile state with compile specific stub method.
IncludePicker::AddTooChainMappings.  This method is where
triple specific libc mappings and libc++ vs libstdcpp mappings
will be done.

This is part 2 of issue 
https://github.com/include-what-you-use/include-what-you-use/issues/669

### CODE REVIEW

**Comment by kimgr** [comment]
This looks like it introduces significant ownership confusion and mutable global state. Can you say something about why this is necessary and what you wanted to achieve? There must be a simpler way to get there.

**Comment by trixirt** [comment]
The target and c++ lib state need by the new target specific include mapper is held by the global compiler instance state.  The existing globals needed to be improved to make this visible to the lower levels. This could have been done by adding a few more global variables but it seemed like moving the effected variables into a class would be a better long term path.    A side effect of using the compiler instance late required some other global state to be saved in the IwyuDriver class. The other global were left as-is but should likely get a similar global-to-class makeover.

**Comment by kimgr** [comment]
What would happen if, instead, you added a method to `IncludePicker` to add mappings after construction? It feels like there's probably a natural place in the setup to do this, where all the information is available.

I can take a stab at this when I have some time, but if you want to make a first attempt, please do.

Also, naming convention!

**Comment by kimgr** [comment]
I'm pretty sure this is the wrong way to solve this problem. If/when I can find some time, I'll try to propose a simpler alternative as suggested above.

**Comment by kimgr** [comment]
Closing this to clean up the list of open MRs. As mentioned earlier, I think there are better ways to do this. Will investigate at some point.

**Pull request closed without merging**
