### PR TITLE
Remove logging from FindArgumentsToDefined

### PR DESCRIPTION
**Pull request by kimgr**
This came up in issue #325, and I've always found this logging to be in the way.

If we think it might be useful, I could increase the log level instead.

### CODE REVIEW

**Comment by kimgr** [comment]
OK, makes sense. Let me recast the patch.

**Comment by kimgr** [comment]
Done, PTAL.

**Comment by vsapsai** [comment]
Looks good to me. And it doesn't contradict to [verbosity description in `iwyu_globals.h`](https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_globals.h#L73).

**Comment by vsapsai** [comment]
Merged in 0cfdff27dce040787499c77f01237b99482ea70e.

**Pull request closed without merging**
