### PR TITLE
fix a bug

### PR DESCRIPTION
**Pull request by xuzhen1994**
Filepath may contains the symbol ":" in Windows, and the line break is different.

### CODE REVIEW

**Comment by kimgr** [comment]
Thanks!

I'm surprised your changes work, though...

Won't `(.*)` eagerly consume the trailing `:`? I would expect you'd need non-greedy matching here.

Also, doesn't `$` match `\r\n` on Windows and `\n` on Unix?

**Comment by Bu11etmagnet** [comment]
Maybe he's running iwyu compiled on Windows from a Python script running on Unix?

**Comment by kimgr** [comment]
I completely misread this patch -- I thought it was for iwyu_tool.py.

fix_includes.py, on the other hand, has tests -- can you add test cases for the stuff that doesn't work prior to your patch?

**Comment by kimgr** [comment]
No input for more than six months. I've added a new PR with tests based on this one. Closing.

**Pull request closed without merging**
