### PR TITLE
Move autocast testing from badinc

### PR DESCRIPTION
**Pull request by bolshakov-a**

### CODE REVIEW

**Comment by kimgr** [comment]
Let's go even smaller. If you could do one commit at a time, we'll have CI support to make sure every commit works.

**Comment by kimgr** [comment]
(I merged a test suite fix on master, btw)

**Comment by bolshakov-a** [comment]
> Let's go even smaller. If you could do one commit at a time, we'll have CI support to make sure every commit works.

Did I understand correctly that you mean pushing commits separately? I've done.

**Comment by kimgr** [comment]
I meant let's open one PR for every commit for these cleanup changes. It's easier to review that way.

The Apply formatting commit looks a little odd in the middle there, but I need to look into that and see if it should be squashed or further separated.

**Comment by bolshakov-a** [comment]
Ok

**Comment by bolshakov-a** [comment]
So, separate PR for "Apply formatting" too? Or maybe just one PR for it and its parent commit?

**Review by kimgr — APPROVED** [review]

**Pull request merged**
