### PR TITLE
Generate IncludeMapEntry tables from respective *.imp files.

### PR DESCRIPTION
**Pull request by trixirt**
iwyu_include_picker.cc's IncludeMapEntry tables duplicate in c form
several external imp file.  To remove this duplication, the c form
will be generated as part of the build process.  The generator is the
imp2array.py script.  It is called.

`imp2array.py -i <input-file> -o <output-file> -n <name-of-table>`

### CODE REVIEW

**Comment by trixirt** [comment]
For issue https://github.com/include-what-you-use/include-what-you-use/issues/669
shows generated tables without replacing existing.

**Comment by trixirt** [comment]
Shows a replacement and how it was verified.

**Comment by trixirt** [comment]
Generated tables verified and old tables removed.
All changes done.
Ready to go.

**Comment by trixirt** [comment]
Any comments ?

**Comment by kimgr** [comment]
I'm sorry I haven't followed up on this properly. I need some time to review this in detail, but I think the overall direction is great!

It looks like your commit is doing at least three things at once; I'd prefer if you put the mechanism in place for generating .h from .imp first, and then ported the .imp files over one by one. Renaming and adding symbols must be separate commits, because they are functional (possibly breaking) changes.

**Comment by trixirt** [comment]
I am no longer working on iwyu.

**Comment by kimgr** [comment]
Closing this to clean up the list of open MRs. I think the idea is sound, and I'll make an effort to resurrect it at some point in the future.

**Pull request closed without merging**
