### PR TITLE
Add --no_fwd_decls option

### PR DESCRIPTION
**Pull request by alex-xnor**
As requested in #354. Marks all uses as full uses. Useful for compliance with Google C++ style guide.

### CODE REVIEW

**Comment by kimgr** [comment]
Cool, thanks! Can you also add a test case to prove this behavior exists? There's a list of per-testcase IWYU switches in `run_iwyu_tests.py` where you can add `--no_fwd_decls` for your new test to check that it short-circuits the include analysis.

**Comment by alex-xnor** [comment]
Sure. I added a test.

**Comment by kimgr** [comment]
Looks great to me. Could you squash the commits with a message mentioning the fixed issue as well? And then just force-push over the PR branch, and I can merge to master. Thank you!

**Comment by cdglove** [comment]
How does this handle the case where a fwd decl is required? Sometimes it's not possible to #include due to circular dependencies so I assume that in those cases the build will break and someone will need to mark the decl as "IWYU keep"?

**Comment by kimgr** [comment]
Oops, this should also target the master branch, not clang_4.0

**Comment by alex-xnor** [comment]
@kimgr Done.

@cdglove I didn't consider that case, but experimentally it looks like it will suggest removing the required forward declaration (which would break compilation); adding `// IWYU pragma: keep` as you mention does work to prevent it from suggesting removal of the required forward declaration. I haven't thought about that situation very much so I'm not sure if this behavior is reasonable or not.

**Comment by kimgr** [comment]
@cdglove I think that's a case of "Doctor, it hurts when I pass this flag" -- if you're modding IWYU's default behavior to never forward-declare, then it's hard for it to do the right thing.

But maybe it would be nice if it only forward-declared when it was absolutely  necessary. I don't really have a good idea for how to do that.

**Pull request merged**
