### PR TITLE
FreeBSD target specific include mapping

### PR DESCRIPTION
**Pull request by trixirt**
Uses the imp to header generator
https://github.com/include-what-you-use/include-what-you-use/pull/671

Uses the target specific include mapping infra
https://github.com/include-what-you-use/include-what-you-use/pull/680

Adds FreeBSD as an example.

This should be all that is needed for this issue: 
https://github.com/include-what-you-use/include-what-you-use/issues/669

### CODE REVIEW

**Comment by trixirt** [comment]
Any comments ?

**Comment by kimgr** [comment]
Sorry, spring-time is always a time of perfect work/life balance -- too much to do on both fronts :)

I'll circle back to this eventually. If you want to do prep in the meantime, please take some time to look over naming -- we should be using `lower_case_with_underscores`, not LLVM-style's `PascalCase` for variables.

Thanks!

**Comment by kimgr** [comment]
I like how this patch builds on the other two, and does exactly one thing.

Just so I understand -- I'm an occasional FreeBSD user, so I should be able to test this for real at some point, but I'm also not intimately familiar with the platform -- are these libc headers for FreeBSD or the kernel headers?

It would be nice if we could be as specific as possible in the mapping names, regarding what they cover. For a "platform", I guess there are two-three mappings we care about: C stdlib, C++ stdlib and possibly kernel headers (?). Keeping these as separate mapping files should make it easier to (re-)generate. Does that make sense?

**Comment by kimgr** [comment]
Closing this to clean up the list of open MRs. Platform-specific mappings are an interesting problem, but as mentioned above I'm not sure exactly how to key them. This branch will prove useful when I can circle back to it.

**Pull request closed without merging**
