### PR TITLE
Moving-around/deduping boost/numeric/odeint mappings

### PR DESCRIPTION
**Pull request by pppyx**
Remove circular boost/numeric/odeint mappings

### CODE REVIEW

**Comment by kimgr** [comment]
Commit message is misleading now, you're not adding any comments :)

**Comment by kimgr** [comment]
`git commit --amend` on the branch and remove the comment part of the commit message.

**Comment by pppyx** [comment]
commit message fixed

**Comment by kimgr** [comment]
I'm sorry. Now I see that the top added lines _are_ in fact comments, not moved/deduped lines.

I think the commit message I would like to see is simply:
```
Remove circular boost/numeric mappings
```

Could you amend once more, and I can merge? Thanks.

**Comment by pppyx** [comment]
amended:)

**Comment by kimgr** [comment]
@ppyx I meant the commit message, not the PR title.

**Comment by pppyx** [comment]
Do you mean restore PR title to its original state? I have changed the commit message.

**Comment by kimgr** [comment]
Hmm, OK... I still see the old commit message here: https://github.com/include-what-you-use/include-what-you-use/pull/842/commits

**Comment by kimgr** [comment]
I fixed this up locally and merged with an additional commit to clean up the comment section so it doesn't look like mappings. Thanks for the original patch!

**Pull request closed without merging**
