### PR TITLE
Fix issue 163: briefer why comments.

### PR DESCRIPTION
**Pull request by kimgr**
Instead of reserving the last 5 chars for ', etc' in why comments, just
truncate the last symbol with '...'. This generally gives more relevant
output.

### CODE REVIEW

**Comment by kimgr** [comment]
ref issue #163

**Comment by LegalizeAdulthood** [comment]
Try running it on the code referenced in that issue.  If you get some reasonable sense of why it wants to include `<ext/alloc_traits.h>`, or even better, it no longer nags me that I need to include this implementation detail header, then it's fixed.  I'm a user of iwyu, not a developer, so having me review the code is rather pointless.  If this changeset fixes the issue, great, otherwise, the issue is still open.

**Comment by kimgr** [comment]
Sorry, yes, I meant if you could run a patched IWYU against the code in question, and get the behavior you expect. I don't have a gcc/libstdc++ environment where I can reproduce the original issue.

The problem with the private symbol leaking out is not fixed, only the disappearing "// for ..." comment. We pulled the functional bug out into a separate issue, #166.

**Comment by vsapsai** [comment]
First of all, I don't like the name `Truncate`, it is too generic. Sorry, right now I don't have a better suggestion.

And now let's get to edge cases. Can we get `  // f...`? I.e. part of "for" and space are truncated. It looks pretty ugly.

Can we get something like `  // for T...`? It is ugly, but we can live with it and I'm not sure it is bad. When it is the only visible symbol, it is good to indicate there is a truncated string. But if we have something like `  // for vector, remove_if, T...`, then "etc." looks nicer.

I've noticed you increased `max_length` by 1. Have you checked that clang-format excludes new line characters when enforces line length limit? It shouldn't be an issue, just need to check it.

**Comment by kimgr** [comment]
> I've noticed you increased max_length by 1. Have you checked that clang-format excludes
> new line characters when enforces line length limit? It shouldn't be an issue, just need to check it.

Oops, no the convention seems to be to put the newline at col 80, so the max width should be 79, as it was.

As for the rest, I think they are all possible, depending on how long your include lines are. I wish we had test coverage for this, so it was easier to experiment.

I'll come back with an updated patch, thanks for reviewing!

**Comment by kimgr** [comment]
Oops, I accidentally killed this. Updated in new PR #204.

I addressed everything but this comment

> But if we have something like // for vector, remove_if, T..., then "etc." looks nicer.

It could probably be made to work, but I didn't want to introduce even more complexity for the sake of this corner case.

**Pull request closed without merging**
