### PR TITLE
Misc: Add a script to generate Boost mapping files

### PR DESCRIPTION
**Pull request by zaufi**
Some parts of the script based on comments found in existed `boost*.imp` files. The last Boost version the script has been used/tested is 1.70. The result imports definitely far from being complete, but already has used to lint some internal code and I found them pretty useful. But of course, any further additions/improvements are quite possible and welcomed.

### CODE REVIEW

**Comment by kimgr** [comment]
Thank you, this looks really nice.

Is there any chance to port the shell script to Python? We try to cater to platforms where there is no shell as well as platforms without `bash`.

**Comment by kimgr** [comment]
@zaufi Ping -- would you consider porting this to Python? Otherwise I can try and pick it up, but I can't promise when.

**Comment by zaufi** [comment]
@kimgr 

Nowadays I've stopped actively using IWYU due to #759 that is quite painful to me. But if you have a chance to look at it and maybe give me some advice (or maybe even a fix... the PR 727 mentioned looks promising to my amateur eye %) I'll port it quickly :)

**Comment by kimgr** [comment]
Not moving forward. Closing for now.

**Comment by danielh2942** [comment]
I made some slight alterations to it as it seems to not work very well with boost/test and boost/preprocessor
this may possibly cause issues with libraries beyond boost/test and boost/regex
```
# it kind of freaks out with windows line endings if your version of boost has them so this scrubs them away
25a26
>   | sed -e 's/\r//g' \
103a105,106
# add unit_test and test_tools to facade headers
>   test/unit_test.hpp \
>   test/test_tools.hpp \
# Change the perl outputs from "<path>" to "\"path\"" because rules seem to apply to both if the includes are surrounded by quotations
116c119
<   | perl -nle 'm/^([^:]+).*["<]([^>]+)[">]/ && print qq@    { include: ["<$2>", private, "<$1>", private ] },@' \
---
>   | perl -nle 'm/^([^:]+).*["<]([^>]+)[">]/ && print qq@    { include: ["\\"$2\\"", private, "<$1>", private ] },@' \
135c138
<   | perl -nle 'm/^([^:]+).*["<]([^>]+)[">]/ && print qq@    { include: ["<$2>", private, "<$1>", public ] },@' \
---
>   | perl -nle 'm/^([^:]+).*["<]([^>]+)[">]/ && print qq@    { include: ["\\"$2\\"", private, "<$1>", public ] },@' \
158c161
<       | perl -nle 'm/^([^:]+).*["<]([^>]+)[">]/ && print qq@    { include: ["<$2>", public, "<$1>", public ] },@' \
---
>       | perl -nle 'm/^([^:]+).*["<]([^>]+)[">]/ && print qq@    { include: ["\\"$2\\"", public, "<$1>", public ] },@' \
# add some excludes from public-public.imp as I need to assign blanket rules at the bottom
163c166,171
<         -e '/boost\/version\.hpp/d'
---
>         -e '/boost\/version\.hpp/d' \
>         -e '/boost\/test\/auto_unit_test\.hpp/d' \
>         -e '/boost\/test\/unit_test_suite.hpp/d' \
>         -e '/boost\/test\/tools\/*/d' \
>         -e '/boost\/test\/utils\/*/d' \
>         -e '/boost\/preprocessor\/*/d'
# reassign some headers
180a189,194
>     { include: ["@\"boost/regex/.*\"", private, "<boost/regex.hpp>", public ] },
>     { include: ["@<boost/test/tools/.*>", private, "<boost/test/test_tools.hpp>", public ] },
>     { include: ["@\"boost/test/tools/.*\"", private, "<boost/test/test_tools.hpp>", public ] },
>     { include: ["\"boost/test/unit_test_suite.hpp\"", private, "<boost/test/unit_test.hpp>", public ] },
>     { include: ["\"boost/test/auto_unit_test.hpp\"", private, "<boost/test/unit_test.hpp>", public ] },
>     { include: ["@\"boost/test/utils/.*\"", private, "<boost/test/unit_test.hpp>", public ] },
```

**Pull request closed without merging**
