### PR TITLE
Fix up LLVM APT packages in CI

### PR DESCRIPTION
**Pull request by kimgr**

### CODE REVIEW

**Comment by kimgr** [comment]
@sylvestre I've been struggling with the Ubuntu Jammy snapshot packages for a while. This workaround is kind-of nuclear, but it seems to work. Does this give you any detail that might indicate a bug on the llvm-toolchain side? Is there a more obvious workaround? I think I convinced myself that I could also install a bunch of extra packages, and it would solve everything except the soname symlink issue. Grateful for any hints.

**Comment by kimgr** [comment]
Replaced by #1632

**Comment by sylvestre** [comment]
yeah, sorry, I will have a look, sorry

**Comment by kimgr** [comment]
@sylvestre no worries, and thank you! I wish I understood the debian packaging enough to help with patches 🙂

**Comment by sylvestre** [comment]
@kimgr I think it is now fixed :)

**Comment by kimgr** [comment]
@sylvestre oh, cool! I'll try disabling these workarounds tomorrow and we'll see how it goes. Thanks!

**Pull request closed without merging**
