### PR TITLE
Add docs for always_keep pragma

### PR DESCRIPTION
**Pull request by kadircet**

### CODE REVIEW

**Comment by kimgr** [comment]
Discussions on pragma naming ongoing in: https://github.com/include-what-you-use/include-what-you-use/issues/1235

**Comment by kadircet** [comment]
rebase to pick up CI fix.

Fixes https://github.com/include-what-you-use/include-what-you-use/issues/1235.

**Comment by kadircet** [comment]
> Might be a good idea to also cover always_keep in the summary section at the end: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#which-pragma-should-i-use.

Thanks, updated that part too.

> We can't really merge this until the pragma is implemented. The semantics look right to me, do you want to take a stab at it, or should I?

It'd be great if you can take a stab at that, as I am not really familiar with the codebase

**Comment by kadircet** [comment]
hi! did you get a chance to look at the implementation here?

i am planning to introduce this pragma handling to LLVM soon, it'd be quite useful if the docs are updated for that one.

**Comment by kimgr** [comment]
I haven't had a chance yet, but I'll try to get this in motion.

**Comment by kimgr** [comment]
Superseded by full implementation in https://github.com/include-what-you-use/include-what-you-use/pull/1272

**Pull request closed without merging**
