### PR TITLE
Always use one-line messages with --output-format=clang

### PR DESCRIPTION
**Pull request by svenpanne**
Apart from being easier to read by humans, this improves the cooperation
with other tools (e.g. Jenkins' warnings-ng plugin, various Emacs modes)
quite a bit. As an example, here the previous output:

    Foo.h:1:1: error: add the following line
    class Bar;
    Foo.h:18:1: error: remove the following line
    #include "Bar.h"
    Foo.cc:1:1: error: add the following line
    #include "Baz.h"          // for Huey, Dewey, Louie (ptr only)
    Foo.cc:19:1: error: remove the following line
    #include "Blah.h"

With this patch:

    Foo.h:1:1: error: add 'class Bar;'
    Foo.h:18:1: error: superfluous '#include "Bar.h"'
    Foo.cc:1:1: error: add '#include "Baz.h"' (for Huey, Dewey, Louie (ptr only))
    Foo.cc:19:1: error: superfluous '#include "Blah.h"'

### CODE REVIEW

**Comment by kimgr** [comment]
Nice! Something was off with notifications, so I just saw this PR. I'll look into it in more detail tomorrow.

**Comment by kimgr** [comment]
Looks good! Can you remove the full stop at the end of the commit subject so it becomes `Always use one-line messages with --output-format=clang`? With that it looks ready to merge.

Thank you.

**Comment by svenpanne** [comment]
> Looks good! Can you remove the full stop at the end of the commit subject so it becomes `Always use one-line messages with --output-format=clang`? [...]

Done.

**Comment by kimgr** [comment]
Beautiful, thanks!

**Pull request merged**
