### PR TITLE
Markdown readme

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

i converted the README into proper markdown for better display on github.
Cheers,
tpltnt

### CODE REVIEW

**Comment by kimgr** [comment]
Thank you!

But I wish you'd asked first; the README was actually generated from the old Google Code wiki content (see `make_readme.py`), now moved into `docs/`.

Do you have a script by any chance, that we could apply to `docs/*.txt` to transform them to Markdown?

**Comment by tpltnt** [comment]
@kimgr no sorry, all done my hand.

**Comment by kimgr** [comment]
I spent an hour on InstructionsForUsers.txt and it turned out quite nice. I'll probably do the same with the other docs, and then update `make_readme.py` to just concatenate them in a reasonable order.

I'll keep this PR open for now, in case I need inspiration for porting.

**Comment by kimgr** [comment]
I now have all source docs ported to Markdown and edited to match the current state of the world (Google Code links redirected to GitHub, build instructions ported to Git, edited for consistency, updated state of Windows support, etc) here:
https://github.com/tpltnt/include-what-you-use/tree/markdown-readme

I'll try to break this up into smaller increments to form a new PR. I vote to close this one.

**Comment by kimgr** [comment]
I believe this is now solved more properly, i.e. all docs are converted to Markdown, and README.md is generated from said docs. Thanks for starting up this work!

**Pull request closed without merging**
