### PR TITLE
Fix #245: SOCK_STREAM attributed to bits/socket_type.h

### LINKED ISSUE #245: including <bits/socket_type.h> is suggested by iwyu, while the file itself forbids it
i just tried iwyu on [cern root](https://github.com/pseyfert/root/tree/includewhatyouneed). Mostly successful. (I also saw #90)
One file which gets wrongly suggested to me is:
> /home/pseyfert/coding/ROOT6/roofit/roofitcore/src/BidirMMapPipe.cxx should add these lines:
> #include <bits/socket_type.h>           // for SOCK_STREAM
when doing so, compilation fails because bits/socket_type.h contains the lines:
> #ifndef _SYS_SOCKET_H
> # error "Never include <bits/socket_type.h> directly; use <sys/socket.h> instead."
> #endif
(socket.h is also suggested, they only end up in the wrong order)

### PR DESCRIPTION
**Pull request by kimgr**
Add mapping from bits/socket_type.h -> sys/socket.h.

### CODE REVIEW

**Comment by vsapsai** [comment]
Please also add the mapping to gcc.libc.imp. And I was thinking about adding to mappings derived from
`# error "Never use <bits/dlfcn.h> directly; include <dlfcn.h> instead."`
also mappings derived from
`# error "Never include <bits/socket_type.h> directly; use <sys/socket.h> instead."`

With the command
`grep -R '^ *# *error "Never use\|include' * | perl -nle 'm/<([^>]+).*directly.*<([^>]+)/ && print qq@    { "<$1>", kPrivate, "<$2>", kPublic },@' | sort`

I received following 93 mappings (some of them already present):
```
    { "<bits/a.out.h>", kPrivate, "<a.out.h>", kPublic },
    { "<bits/byteswap-16.h>", kPrivate, "<byteswap.h>", kPublic },
    { "<bits/byteswap.h>", kPrivate, "<byteswap.h>", kPublic },
    { "<bits/cmathcalls.h>", kPrivate, "<complex.h>", kPublic },
    { "<bits/confname.h>", kPrivate, "<unistd.h>", kPublic },
    { "<bits/dirent.h>", kPrivate, "<dirent.h>", kPublic },
    { "<bits/dlfcn.h>", kPrivate, "<dlfcn.h>", kPublic },
    { "<bits/elfclass.h>", kPrivate, "<link.h>", kPublic },
    { "<bits/endian.h>", kPrivate, "<endian.h>", kPublic },
    { "<bits/epoll.h>", kPrivate, "<sys/epoll.h>", kPublic },
    { "<bits/error.h>", kPrivate, "<error.h>", kPublic },
    { "<bits/eventfd.h>", kPrivate, "<sys/eventfd.h>", kPublic },
    { "<bits/fcntl2.h>", kPrivate, "<fcntl.h>", kPublic },
    { "<bits/fcntl.h>", kPrivate, "<fcntl.h>", kPublic },
    { "<bits/fcntl-linux.h>", kPrivate, "<fcntl.h>", kPublic },
    { "<bits/fenv.h>", kPrivate, "<fenv.h>", kPublic },
    { "<bits/huge_valf.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/huge_val.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/huge_vall.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/hwcap.h>", kPrivate, "<sys/auxv.h>", kPublic },
    { "<bits/inf.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/in.h>", kPrivate, "<netinet/in.h>", kPublic },
    { "<bits/inotify.h>", kPrivate, "<sys/inotify.h>", kPublic },
    { "<bits/ioctls.h>", kPrivate, "<sys/ioctl.h>", kPublic },
    { "<bits/ioctl-types.h>", kPrivate, "<sys/ioctl.h>", kPublic },
    { "<bits/ipc.h>", kPrivate, "<sys/ipc.h>", kPublic },
    { "<bits/ipctypes.h>", kPrivate, "<sys/ipc.h>", kPublic },
    { "<bits/libio-ldbl.h>", kPrivate, "<libio.h>", kPublic },
    { "<bits/link.h>", kPrivate, "<link.h>", kPublic },
    { "<bits/locale.h>", kPrivate, "<locale.h>", kPublic },
    { "<bits/mathcalls.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/mathdef.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/math-finite.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/mathinline.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/mman.h>", kPrivate, "<sys/mman.h>", kPublic },
    { "<bits/mman-linux.h>", kPrivate, "<sys/mman.h>", kPublic },
    { "<bits/monetary-ldbl.h>", kPrivate, "<monetary.h>", kPublic },
    { "<bits/mqueue2.h>", kPrivate, "<mqueue.h>", kPublic },
    { "<bits/mqueue.h>", kPrivate, "<mqueue.h>", kPublic },
    { "<bits/msq.h>", kPrivate, "<sys/msg.h>", kPublic },
    { "<bits/nan.h>", kPrivate, "<math.h>", kPublic },
    { "<bits/netdb.h>", kPrivate, "<netdb.h>", kPublic },
    { "<bits/param.h>", kPrivate, "<sys/param.h>", kPublic },
    { "<bits/poll2.h>", kPrivate, "<sys/poll.h>", kPublic },
    { "<bits/poll.h>", kPrivate, "<sys/poll.h>", kPublic },
    { "<bits/printf-ldbl.h>", kPrivate, "<printf.h>", kPublic },
    { "<bits/resource.h>", kPrivate, "<sys/resource.h>", kPublic },
    { "<bits/sched.h>", kPrivate, "<sched.h>", kPublic },
    { "<bits/select2.h>", kPrivate, "<sys/select.h>", kPublic },
    { "<bits/select.h>", kPrivate, "<sys/select.h>", kPublic },
    { "<bits/semaphore.h>", kPrivate, "<semaphore.h>", kPublic },
    { "<bits/sem.h>", kPrivate, "<sys/sem.h>", kPublic },
    { "<bits/setjmp2.h>", kPrivate, "<setjmp.h>", kPublic },
    { "<bits/setjmp.h>", kPrivate, "<setjmp.h>", kPublic },
    { "<bits/shm.h>", kPrivate, "<sys/shm.h>", kPublic },
    { "<bits/sigaction.h>", kPrivate, "<signal.h>", kPublic },
    { "<bits/sigcontext.h>", kPrivate, "<signal.h>", kPublic },
    { "<bits/signalfd.h>", kPrivate, "<sys/signalfd.h>", kPublic },
    { "<bits/socket2.h>", kPrivate, "<sys/socket.h>", kPublic },
    { "<bits/socket.h>", kPrivate, "<sys/socket.h>", kPublic },
    { "<bits/socket_type.h>", kPrivate, "<sys/socket.h>", kPublic },
    { "<bits/statfs.h>", kPrivate, "<sys/statfs.h>", kPublic },
    { "<bits/stat.h>", kPrivate, "<sys/stat.h>", kPublic },
    { "<bits/statvfs.h>", kPrivate, "<sys/statvfs.h>", kPublic },
    { "<bits/stdio2.h>", kPrivate, "<stdio.h>", kPublic },
    { "<bits/stdio.h>", kPrivate, "<stdio.h>", kPublic },
    { "<bits/stdio-ldbl.h>", kPrivate, "<stdio.h>", kPublic },
    { "<bits/stdio_lim.h>", kPrivate, "<stdio.h>", kPublic },
    { "<bits/stdlib-float.h>", kPrivate, "<stdlib.h>", kPublic },
    { "<bits/stdlib.h>", kPrivate, "<stdlib.h>", kPublic },
    { "<bits/stdlib-ldbl.h>", kPrivate, "<stdlib.h>", kPublic },
    { "<bits/string2.h>", kPrivate, "<string.h>", kPublic },
    { "<bits/string3.h>", kPrivate, "<string.h>", kPublic },
    { "<bits/string.h>", kPrivate, "<string.h>", kPublic },
    { "<bits/stropts.h>", kPrivate, "<stropts.h>", kPublic },
    { "<bits/syscall.h>", kPrivate, "<sys/syscall.h>", kPublic },
    { "<bits/sys_errlist.h>", kPrivate, "<stdio.h>", kPublic },
    { "<bits/syslog.h>", kPrivate, "<sys/syslog.h>", kPublic },
    { "<bits/syslog-ldbl.h>", kPrivate, "<sys/syslog.h>", kPublic },
    { "<bits/termios.h>", kPrivate, "<termios.h>", kPublic },
    { "<bits/timerfd.h>", kPrivate, "<sys/timerfd.h>", kPublic },
    { "<bits/typesizes.h>", kPrivate, "<sys/types.h>", kPublic },
    { "<bits/uio.h>", kPrivate, "<sys/uio.h>", kPublic },
    { "<bits/unistd.h>", kPrivate, "<unistd.h>", kPublic },
    { "<bits/ustat.h>", kPrivate, "<sys/ustat.h>", kPublic },
    { "<bits/utmp.h>", kPrivate, "<utmp.h>", kPublic },
    { "<bits/utmpx.h>", kPrivate, "<utmpx.h>", kPublic },
    { "<bits/utsname.h>", kPrivate, "<sys/utsname.h>", kPublic },
    { "<bits/waitflags.h>", kPrivate, "<sys/wait.h>", kPublic },
    { "<bits/waitstatus.h>", kPrivate, "<sys/wait.h>", kPublic },
    { "<bits/wchar2.h>", kPrivate, "<wchar.h>", kPublic },
    { "<bits/wchar-ldbl.h>", kPrivate, "<wchar.h>", kPublic },
    { "<bits/xtitypes.h>", kPrivate, "<stropts.h>", kPublic },
```

"directly" in Perl regexp is to filter out HTML tags like `{ "<code>", kPrivate, "</code>", kPublic },`.

**Comment by kimgr** [comment]
Thanks!

I still think it would be better to do this at run-time, as sketched out in #109, similar to how we handle @headername in comments.

That way we can kill off lots of mappings where libraries already do this.

**Comment by kimgr** [comment]
> That way we can kill off lots of mappings where libraries already do this.

But your Perl example made it clear that my "generalized" matching will not work. I think it would be better to add these two exact patterns for glibc, and add new ones for other libs as they come up.

**Comment by vsapsai** [comment]
I like the idea of detecting include rules at runtime. But at the moment we are just modifying mappings so I think it is better to add a different error pattern to grep+perl command.

**Comment by ThosRTanner** [comment]
what are kPrivate and kPublic?

**Comment by vsapsai** [comment]
kPrivate and kPublic are in-code equivalents of private and public used in *.imp files. These enum values are defined [here](https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_include_picker.h#L68). Mapping for *.imp file is semantically the same but format is slightly different, something like `{ include: [ "<bits/a.out.h>", private, "<a.out.h>", public ] }`

Qt and Boost mappings are provided in *.imp files because they are optional and useful when you use corresponding library. We tried to keep mappings for libc and libstdc++ the same way but it turned out without them IWYU is practically useless and confusing to users. To avoid extra work from users we add these mappings automatically in code.

**Comment by kimgr** [comment]
Update the PR to add the mapping to gcc.libc.imp as well. Can we close this and deal with the others separately?

I didn't understand this comment entirely:

> I like the idea of detecting include rules at runtime. But at the moment we are just modifying
> mappings so I think it is better to add a different error pattern to grep+perl command.

Would you like me to pick up #109 again and clean up the parsing of `#error` directives? I'd be happy to do so, I think it would more or less permanently fix mapping problems for glibc.

**Comment by vsapsai** [comment]
I agree to merge in this one and I'll submit a PR with other mapping(s). After checking there is only one new `{ "<bits/typesizes.h>", kPrivate, "<sys/types.h>", kPublic }`.

As for #109, you can pick it up again, I need to check again what was my idea.

**Comment by vsapsai** [comment]
As promised, I've added a mapping in [my fork](https://github.com/vsapsai/include-what-you-use/commit/63b53d202f9a954814bc9f477987574bfeeccaa8). I didn't submit a pull request because it is likely to be subsumed by [PR #255 "Fix #109: synthesize mappings from #error directives"](https://github.com/include-what-you-use/include-what-you-use/pull/255).

**Comment by kimgr** [comment]
Let's pull in your additional mapping as well, since the #109 fix is put to rest for now. Can you create a PR?

**Comment by vsapsai** [comment]
Submitted PR #260.

**Pull request merged**
