### PR TITLE
Add --silence_correct option for iwyu, tests, docs

### PR DESCRIPTION
**Pull request by danielh2942**
this was requested by #999 and #1130, it adds the
ability to suppress correct includes messages, to
reduce the noise of output generated by IWYU

wrote some tests and updated documentation to reflect the change
this nullifies all output for verbose levels <= 3

### CODE REVIEW

**Comment by firewave** [comment]
Very cool.

The option name feels a bit off though.

Could you maybe also look into implementing #998? The option could be renamed into something like `--output=` which takes `quiet` (this PR), `full` (my other suggestion) or `normal` (default - the name feels off, too).

**Comment by firewave** [comment]
@danielh2942 
Thanks for pointing that out. Looks good.

It still prints the `should x these lines:` messages though. But it does this regardless of the findings. Maybe these could be suppressed if they contain no information - possibly via the proposed `--output=`.

**Comment by danielh2942** [comment]
I'll have a look into this, I'll have to make sure that none of the affiliated python scripts break by the change in output and stuff so it might take a while.

**Comment by kimgr** [comment]
Sorry to put a damper on this, but I really want to avoid messing with the IWYU output format. since it's being parsed by:

* Our tests
* iwyu_tool.py
* fix_includes.py
* CMake's IWYU mode

While I agree that it's horrendously ugly, forking into multiple output formats now will just create a lot of low-value complexity (more code to maintain, more tests to maintain, more difficult to integrate tools, etc, etc).

I can only recommend to wrap `include-what-you-use` with a script if you want to tweak output format.

**Comment by danielh2942** [comment]
Cool, got it. closing.

**Comment by firewave** [comment]
> While I agree that it's horrendously ugly, forking into multiple output formats now will just create a lot of low-value complexity (more code to maintain, more tests to maintain, more difficult to integrate tools, etc, etc).

In that case it should have a proper parsable output format instead (I prefer JSON but the world might disagree) - which could also be configured by `--output=`.

**Pull request closed without merging**
