### PR TITLE
Fix some Clang-tidy warnings

### PR DESCRIPTION
**Pull request by EugeneZelenko**

### CODE REVIEW

**Comment by kimgr** [comment]
Cool, thanks! Can you share the clang-tidy command-line you're using? I've tried to use it locally, but got swamped in identifier-naming output.

**Comment by EugeneZelenko** [comment]
Actually you could setup readability-identifier-naming in .clang-tidy (see LLVM one in root directory) if they are different from LLVM when you build in-tree or when you build out-of-tree.

My regular minor cleanup command line is:

-checks="-*,misc-suspicious-string-compare,misc-unused-using-decls,modernize-redundant-void-arg,modernize-deprecated-headers,modernize-use-bool-literals,modernize-use-nullptr,modernize-use-override,readability-container-size-empty,readability-redundant-control-flow,readability-redundant-string-cstr,readability-redundant-string-init,readability-simplify-boolean-expr,readability-redundant-string-init" -config="{CheckOptions: [{key: misc-suspicious-string-compare.WarnOnLogicalNotComparison , value: '1'}]}" -header-filter=".*"

I also run -checks="-*,modernize-*", but I didn't fix all of them. For example, I broke GCC 4.7 build bots with fixing modernize-use-default, but they may be irrelevant to IWYU.

**Comment by vsapsai** [comment]
@EugeneZelenko, is it better to have one PR with all Clang-tidy fixes? Currently it looks like unnecessary overhead to review different files in different pull requests. But probably I'm missing some obvious reason.

**Comment by EugeneZelenko** [comment]
Sorry, I was not able to figure out how to make my local branch visible to GitHub.

**Comment by kimgr** [comment]
Something like:

    $ git checkout localbranch 
    $ git push origin localbranch:localbranch

assuming `origin` points to your GitHub fork?

**Comment by EugeneZelenko** [comment]
Actually I tried this before but I got:

error: The requested URL returned error: 403 Forbidden while accessing https://github.com/include-what-you-use/include-what-you-use.git/info/refs

fatal: HTTP request failed

May be RHEL 6 git 1.7.1 is too old.

**Comment by daveisfera** [comment]
On RHEL 6, you can use the git [Software Collection (SCL)](https://access.redhat.com/support/policy/updates/rhscl) for [version 1.9](https://www.softwarecollections.org/en/scls/rhscl/git19/) and [2.5 is available for testing](https://www.redhat.com/archives/sclorg/2016-April/msg00000.html).

**Comment by EugeneZelenko** [comment]
Thank you for suggestion, but I need to bother IT :-(

**Comment by kimgr** [comment]
Ah, the problem is that your `origin` points to the main repo:

>  https://github.com/include-what-you-use/include-what-you-use.git/info/refs

And you don't have write access there.

How did you get the changes up to your fork on GitHub in the first place?

If you don't already have one, you should be able to create a remote for your fork:

    # 'mine' is the alias you use when pushing/pulling. Pick something you like
    # This is a one-time operation to wire your local repo to your remote GitHub repo
    $ git remote add mine https://github.com/EugeneZelenko/include-what-you-use

    # Specify the remote when pushing
    $ git push mine localbranch:localbranch

And you can use `git push -f` to overwrite changes in a PR branch (be careful with this, it rewrites public history, and isn't suitable for much beyond revising PRs).

Hope that helps!

**Comment by EugeneZelenko** [comment]
Thank you for help! And sorry with all newbie questions :-)

Now part of #324.

**Pull request closed without merging**
