### PR TITLE
Fix for #280

### PR DESCRIPTION
**Pull request by pfaffe**
Strip trailing whitespaces and newlines from the dry_run diff output in `fix_includes.py`

### CODE REVIEW

**Comment by kimgr** [comment]
See inline comments. The test case can be simplified. Other than that, the fix looks good.

**Comment by pfaffe** [comment]
Thanks for the review. Applied your comments.

**Comment by kimgr** [comment]
This looks good to me. I'll pull it down, rebase it into a single commit and push it. Thanks for your help!

**Comment by kimgr** [comment]
Pushed manually, now live.

**Pull request closed without merging**
