### PR TITLE
Fix some LLVM STL false positives

### PR DESCRIPTION
**Pull request by EugeneZelenko**
Fix issues I reported in #141.

### CODE REVIEW

**Comment by kimgr** [comment]
Thanks! I see you've followed suit and named it after the larger toolchain (LLVM) instead of the standard library (libc++). I think that was a mistake on my part when I added the `gcc.*` mappings, I didn't fully understand the connection between GCC, libstdc++ and GNU libc at that point (not sure I do still...)

Anyway, I think this would be better named `libcxx.imp`

I know @vsapsai has done some work earlier to have IWYU principally detect patterns in libc++ and report them correctly without mappings. That's of course a much better way forward, but I think this is a good stepping stone to let people use IWYU even if it doesn't really work :-)

Also, I wonder if we should add this to IWYU's builtin mappings in `iwyu_include_picker.cc`. Apple's libc++ seems like a major platform, so it would be nice to support it natively without mappings.

**Comment by EugeneZelenko** [comment]
I think will be good idea to solve libc++ mapping problem ASAP (ether internally or as mapping file). Number of bug reports indicate that it is long overdue feature.

**Comment by vsapsai** [comment]
I see people are eager to help fix handling libc++. I'll try to summarise various issues, clean up my investigation notes and post them.

**Comment by kimgr** [comment]
I'm going to clean this up and commit it. It opens up for people to IWYU with libc++ at their own discretion. I think we can and should do real improvements separately.

**Comment by kimgr** [comment]
Adapted and pushed as 2205f1ac6a2b11352ba1917a9307889a600a0b8f.

**Pull request closed without merging**
