### PR TITLE
Add boost import reference files for version 1.64

### PR DESCRIPTION
**Pull request by scramsby**

### CODE REVIEW

**Comment by kimgr** [comment]
Were these changes generated by the command-lines embedded in the old .imp files? It's always nice if there's a recipe for generating them that doesn't require manual intervention.

I think we should keep the old .imp files and create new, version-tagged ones, so users can choose which mappings they want depending on which Boost version they're using. Can you generate entirely new files called `boost-1.64-all.imp` and `boost-1.64-all-private.imp` instead? Thanks!

**Comment by scramsby** [comment]
These were generated using the script commented at the top of the reference file. I'll make these new versions newly named as you suggest and leave the old.

**Comment by kimgr** [comment]
Commit message now needs some love -- `Re-add` is a little brief :)

**Comment by scramsby** [comment]
Ack! Looks like my rebase went a bit awry there. Will update the commit message.

**Comment by scramsby** [comment]
Done!

**Comment by kimgr** [comment]
Thanks, looks great!

**Pull request merged**
