### PR TITLE
Experiment with a better CMakeLists.txt

### PR DESCRIPTION
**Pull request by kimgr**
Let's see if this builds.

Relies entirely on `find_package` to get at LLVM/Clang build configurations. This gets rid of all duplication of build details from LLVM and Clang.

There are some known issues with Clang packaging, e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862328, so this may prove insufficient for ALL environments, but it should be a good baseline.

### CODE REVIEW

**Comment by kimgr** [comment]
Not looking so good, so far :-)

**Comment by TheErk** [comment]
Did you see you have a version mismatch between llvm/clang in the previous travis log:
```
-- IWYU: found LLVM (version 6.0.0)
-- IWYU: found Clang (at /usr/local/clang-5.0.0)
```

**Comment by TheErk** [comment]
As of today. This branch is fine for my usage as explained in issue #499

**Comment by kimgr** [comment]
This will not be workable until the Debian packaging is fixed, closing.

**Pull request closed without merging**
