### PR TITLE
Use flags to solve the definition-is-use problem

### PR DESCRIPTION
**Pull request by kimgr**
Here's a stab at fixing the problem where IWYU doesn't recognize the definition of free functions as uses of previous declarations of the functions.

This has been reported in #179, and with a slight wrinkle around namespaces in #441.

@bungeman, @EdSchouten, @pseyfert and @Tim020 -- could you take a look and see if this works in your respective contexts? Thanks!

### CODE REVIEW

**Comment by bungeman** [comment]
I just built everything at tip of tree with your patch, and it seems to do the same thing my original patch did but better. I haven't had a lot of time to evaluate, but this seems to fix my issue.

**Comment by pseyfert** [comment]
This fixes the false exclusions I reported in #441.

**Comment by bungeman** [comment]
I think this would also solve #491 .

**Comment by kimgr** [comment]
Thanks for the feedback! I have a foggy idea for an even better design, but I think I'll stop here for now, in the interest of improving user experience.

Thank you @bungeman for the additional bug, I'll double-check that too and make sure it's closed.

**Pull request merged**
