### PR TITLE
More complete usage instructions

### PR DESCRIPTION
**Pull request by kimgr**
Restructure to make room for more run modes
Add section on new CMake support
Add section on iwyu_tool.py

### CODE REVIEW

**Comment by Timmmm** [comment]
That's brilliant, thanks!

**Comment by kimgr** [comment]
Fixed CMake doc links to point to latest version, and not screw up formatting.

**Comment by kimgr** [comment]
Thanks, good input! I'll post a revised version at some point.

**Comment by kimgr** [comment]
Looking at this now, I think title case is pretty annoying -- I've always found it hard to read.

I saw the `Building in-tree` and `Building out-of-tree` headings are both sentence-cased as well, so maybe it's best to leave all level 4 headings in sentence-case now, and I can send a separate patch to kill off title case?

**Comment by kimgr** [comment]
Please take another look.

**Comment by ferdnyc** [comment]
If anyone's looking for data points, I have to agree on title case being annoying — at all heading levels. Wikipedia has finally broken me of the habit of making section headings title-cased, and I couldn't be more relieved.

**Pull request merged**
