### PR TITLE
Allow iwyu_tool.py to accept source paths with symbolic links

### PR DESCRIPTION
**Pull request by EugeneZelenko**

### CODE REVIEW

**Comment by kimgr** [comment]
I think `os.realpath` already does the equivalent of `os.abspath`, can you try removing `abspath`?

**Comment by EugeneZelenko** [comment]
I think will be good idea to ask somebody who knows Python better then me.

**Comment by kimgr** [comment]
I did a few tests, and `os.path.realpath` indeed appears to return absolute paths. I'll fix it up and pushd, thanks!

**Comment by kimgr** [comment]
Fixed in 0341c6c0954ec6c36f2c15b8c3eec4b937039deb.

**Pull request closed without merging**
