### PR TITLE
Mapped `<bits/std_abs.h>` to `<stdlib.h>`

### PR DESCRIPTION
**Pull request by firewave**
Refs #1000.

### CODE REVIEW

**Comment by firewave** [comment]
This fixes the suggestion of the implementation header but afterwards the actual suggestion will flip-flop between `<math.h>` and `<stdlib.h>`.

**Comment by firewave** [comment]
> This fixes the suggestion of the implementation header but afterwards the actual suggestion will flip-flop between `<math.h>` and `<stdlib.h>`.

Maybe this is related to the symbol being attributed to `<stdlib.h>` only in C and `<cstdlib>`/`<cmath>` in C++.

Mapping it to `<stdlib.h>` fixes the flip-flop but will cause correct C++ code using `<cmath>` suggest to use `<stdlib>` instead.

**Comment by kimgr** [comment]
Looks like `<bits/std_abs.h>` is a C++-only header, it's only included from `<cmath>` and `<cstdlib>` on my system:
```
kimgr@lardo:/usr/include$ grep -r "std_abs\.h"
c++/11/cmath:#include <bits/std_abs.h>
c++/11/cstdlib:#include <bits/std_abs.h>
c++/11/bits/std_abs.h:/** @file include/bits/std_abs.h
```

So it can't be right to map the private header to the public C headers (since they never include it).

**Comment by kimgr** [comment]
Hmm, actually, I just stumbled on a bug -- IWYU parses `@file` and `@headername` directives in libstdc++ headers. A bunch of headers are incorrectly marked with `@file include/...actual name...`, which causes IWYU to generate incorrect mappings. Turns out `std_abs.h` is one of them: https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/std_abs.h#L25

**Comment by kimgr** [comment]
I thought I'd fix that bug, and then this PR should not be necessary

**Comment by kimgr** [comment]
This has been fixed by #1598 and #1593 so that mapping for `bits/std_abs.h` happens automatically.

**Pull request closed without merging**
