### PR TITLE
Nothing is eating anything else in this ecosystem

### PR DESCRIPTION
**Pull request by davidfetter**

### CODE REVIEW

**Comment by Bu11etmagnet** [comment]
https://www.merriam-webster.com/dictionary/predates
Note entry 1

**Comment by kimgr** [comment]
Nice! I don't want to give the wrong impression about eating habits.

Could you reword the commit message to have a subject line on imperative form? I usually follow https://chris.beams.io/posts/git-commit/ more or less rigorously. I'd love the current message as body, though.

Thanks!

**Comment by kimgr** [comment]
@davidfetter Do you mind if I apply the patch with your commit message reworded?

**Comment by davidfetter** [comment]
I would be delighted!

**Comment by kimgr** [comment]
Thank you, merged as fb49480.

**Pull request closed without merging**
