### PR TITLE
Support libc++ 17

### PR DESCRIPTION
**Pull request by kon72**
This change updates `libcxx.imp` to match Clang 17.

### CODE REVIEW

**Comment by kimgr** [comment]
Looks good to me. @kilroyd, do you want to take a look?

**Review by kilroyd — APPROVED** [review]
Thanks! Looks good to me too

**Comment by kilroyd** [comment]
Should we cherry pick this into the clang_17 branch?

**Comment by kimgr** [comment]
I try to avoid that, because it's nice if all the communication around the 0.21 release also applies to the clang_17 branch.

**Pull request merged**
