### PR TITLE
Add llvm-toolchain-bionic-12 apt source

### PR DESCRIPTION
**Pull request by storoj**
That change fixes CI builds

### CODE REVIEW

**Comment by kimgr** [comment]
@storoj Thanks, but I think it's the wrong fix or a fix in the wrong place :)

We don't want llvm-12 -- we want the latest snapshot, which now is/should be 13.

The problem (unless I'm missing something) is in LLVM packaging, and should be addressed there.

We sometimes do workarounds for broken packaging, but this is going to bite us, as we want IWYU to follow LLVM mainline. And -12 is now the 12 release branch.

**Comment by storoj** [comment]
@kimgr Yeah, I have the same feelings :)

I just wanted to share an idea of unblocking CI builds for now. But I don't really want this fix to be in the repo. We can close that PR.

**Comment by kimgr** [comment]
I've offered to help out with the LLVM packaging to be able to solve the problem at the root, but I haven't heard back yet. I also don't know a lot about Debian packaging, so I'm probably going to cause more trouble than solutions :-).

But yeah, let's close this. We can afford to fail until LLVM is fixed.

**Comment by storoj** [comment]
@kimgr FYI `llvm-13` is now available, and the current workaround has to be reverted because `/usr/lib/llvm-12/...` is now unavailable.

It turned out that `libomptarget.so.12` is provided by `libomp-dev` package. That package is one of the recommended packages, however Travis uses `--no-install-recommends` option, and that package does not get installed.

Adding `libomp-dev` to the list of packages does not help because it seems that some version of `libomp-dev` (v5 probably) is pre-installed, so the recommended upgrade to v13 does not get installed.

Check out the log of a job from my fork: https://travis-ci.org/github/storoj/include-what-you-use/builds/757494891. That's the output with `libomp-dev` added to the list of packages.

I will add the part of the log here just in case:
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install cmake ninja-build llvm-dev libclang-dev libomp-dev clang
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libopts25 llvm-6.0 llvm-6.0-runtime
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  clang-13 cmake-data lib32gcc1 lib32stdc++6 libarchive13 libc6-i386
  libclang-13-dev libclang-common-13-dev libclang-cpp13 libclang1-13 libllvm13
  libobjc-7-dev libobjc4 libomp5 libpfm4 librhash0 libz3-4 libz3-dev llvm
  llvm-13 llvm-13-dev llvm-13-runtime llvm-13-tools llvm-runtime
  python3-pygments
Suggested packages:
  clang-13-doc cmake-doc lrzip libomp-doc llvm-13-doc ttf-bitstream-vera
Recommended packages:
  libomp-13-dev
The following NEW packages will be installed:
  clang clang-13 cmake cmake-data lib32gcc1 lib32stdc++6 libarchive13
  libc6-i386 libclang-13-dev libclang-common-13-dev libclang-cpp13
  libclang-dev libclang1-13 libllvm13 libobjc-7-dev libobjc4 libomp-dev
  libomp5 libpfm4 librhash0 libz3-4 libz3-dev llvm-13 llvm-13-dev
  llvm-13-runtime llvm-13-tools llvm-dev ninja-build python3-pygments
The following packages will be upgraded:
  llvm llvm-runtime
2 upgraded, 29 newly installed, 0 to remove and 68 not upgraded.
```

**Comment by storoj** [comment]
@kimgr a potentially better workaround is to add `libomp-13-dev` to the list of dependencies, I will try running a job with such an experiment

**Pull request closed without merging**
